---
title: Monitoring Love
timezone: America/New_York
locale: en_us
tagline: 'tagline'
description: 'description'
baseurl: '/'
baseurl_posts_img: '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
disqus: monitoringlove
icon: '/assets/img/icon.png' # [best 300px X 300px]

collections:
  authors:
    title: Authors
    output: true
  uploads:
    title: Uploads
    output: true

defaults:
- scope:
    path: '_posts'
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
